* Praxis - Prayers, Readings and Fasting

This is an [Expo](https://expo.dev) project created with [`create-expo-app`](https://www.npmjs.com/package/create-expo-app).
**Careful**, this app is still under development

** Description
This is a universal mobile app (Android and iOS) for Christians to quickly have access to their daily prayers, scripture readings, and fasting calendar. This current version contains only the Eastern Orthodox daily prayers and calendar, but I intend on adding catholic prayers later on.

** Tasks
- Add a selection of prayer rules, or choice to build your personal. Or just a guide about prayer rules.
- Make icon props for NavButton optional

** Contains
- Orthodox Morning and Evening prayers
- Orthodox daily readings, life of the saints, and fasting calendar
- Languages:
  - English
  - Portuguese
- Calendars:
  - Gregorian
  - Julian

** Coming later
- Psalter
- Bible

** Get started

1. Clone git repo

2. Install dependencies

   ```bash
   npm install
   ```

3. Start the app

   ```bash
    npx expo start
   ```

In the output, you'll find options to open the app in a

- [development build](https://docs.expo.dev/develop/development-builds/introduction/)
- [Android emulator](https://docs.expo.dev/workflow/android-studio-emulator/)
- [iOS simulator](https://docs.expo.dev/workflow/ios-simulator/)
- [Expo Go](https://expo.dev/go), a limited sandbox for trying out app development with Expo

You can start developing by editing the files inside the **app** directory. This project uses [file-based routing](https://docs.expo.dev/router/introduction).


## Learn more

To learn more about developing your project with Expo, look at the following resources:

- [Expo documentation](https://docs.expo.dev/): Learn fundamentals, or go into advanced topics with our [guides](https://docs.expo.dev/guides).
- [Learn Expo tutorial](https://docs.expo.dev/tutorial/introduction/): Follow a step-by-step tutorial where you'll create a project that runs on Android, iOS, and the web.

## Join the Expo community

Join our community of developers creating universal apps.

- [Expo on GitHub](https://github.com/expo/expo): View our open source platform and contribute.
- [Discord community](https://chat.expo.dev): Chat with Expo users and ask questions.
